title: ExoDoxa?
email: aaaaa 
description: >-
  Hoy en la tarde se quemo el arroz y quedo feo :c
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://exodoxa.github.io" # http://localhost:4000/MiSitioWeb/
twitter_username: Esto ya no lo usooo
github_username:  ExoDoxa

# Build settings
theme: minima
plugins:
  - jekyll-feed

